version: "3.9"
services:

  redis:
    container_name: mego_auth_redis
    image: redis:6.2.6-alpine
    ports:
      - "${REDIS_OUTER_PORT}:${REDIS_PORT}"
    volumes:
      - ./tmp/redis:/data
    networks:
      - mego_network

  mego_auth:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mego_auth
    depends_on:
      - redis
    ports:
      - "${AUTH_SERVICE_SERVER_PORT}:${AUTH_SERVICE_SERVER_PORT}"
    networks:
      - mego_network

networks:
  mego_network:
    external: true