version: '3'
dotenv: ['.env']

tasks:
  up:
    cmds:
      - docker-compose  up --build
    silent: true
  down:
    cmds:
      - docker-compose  down
    silent: true
  proto:gen:
    cmds:
      - protoc -I api/proto api/proto/*.proto --go_out=./gen --go_opt=paths=source_relative --go-grpc_out=./gen --go-grpc_opt=paths=source_relative
    silent: true